container:
  image: crystallang/crystal:latest
spec_task:
  env:
    TERM: xterm-256color
  shard_cache:
    fingerprint_script: cat shard.yml
    populate_script: shards install
    folder: lib
  install_expect_script: apt-get update && apt-get install -y expect
  spec_script: unbuffer crystal spec -v
