name: Build FFI Library
description: Build the native libtermisu shared library for CI jobs
runs:
  using: composite
  steps:
    - name: Build native FFI library
      shell: bash
      run: |
        mkdir -p bin
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          crystal build src/termisu.cr --release --cross-compile -o bin/libtermisu
          cc -shared bin/libtermisu.o -o bin/libtermisu.so -L$(crystal env CRYSTAL_LIBRARY_PATH) -lgc -lpthread -ldl
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
          crystal build src/termisu.cr --release --cross-compile \
            --link-flags "$SDKROOT/usr/lib/libiconv.tbd" \
            -o bin/libtermisu
          cc -dynamiclib bin/libtermisu.o -o bin/libtermisu.dylib \
            -Wl,-install_name,@rpath/libtermisu.dylib \
            -L$(crystal env CRYSTAL_LIBRARY_PATH) -lgc -lpthread \
            "$SDKROOT/usr/lib/libiconv.tbd"
        else
          echo "Unsupported RUNNER_OS: $RUNNER_OS"
          exit 1
        fi
