name: Build FFI Library
description: Build the native libtermisu shared library for CI jobs
runs:
  using: composite
  steps:
    - name: Build native FFI library
      shell: bash
      run: |
        mkdir -p bin
        crystal build src/termisu.cr --release --cross-compile -o bin/libtermisu
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          cc -shared bin/libtermisu.o -o bin/libtermisu.so -L$(crystal env CRYSTAL_LIBRARY_PATH) -lgc -lpthread -ldl
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          cc -dynamiclib bin/libtermisu.o -o bin/libtermisu.dylib -L$(crystal env CRYSTAL_LIBRARY_PATH) -lgc -lpthread
        else
          echo "Unsupported RUNNER_OS: $RUNNER_OS"
          exit 1
        fi
