name: Setup Crystal Environment
description: Install Crystal, shards, and build dev dependencies with caching
inputs:
  crystal-version:
    description: Crystal version to install
    required: false
    default: latest
  install-shards:
    description: Whether to run shards install
    required: false
    default: "true"
  build-hace:
    description: Whether to build Hace task runner
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: ${{ inputs.crystal-version }}
    - name: Cache shards
      if: inputs.install-shards == 'true'
      uses: actions/cache@v4
      with:
        path: |
          lib
          bin
          ~/.cache/shards
        key: ${{ runner.os }}-shards-${{ hashFiles('shard.lock', 'shard.yml') }}
        restore-keys: |
          ${{ runner.os }}-shards-
    - name: Install shards
      if: inputs.install-shards == 'true'
      shell: bash
      run: shards install
    - name: Build Hace
      if: inputs.build-hace == 'true' && inputs.install-shards == 'true'
      shell: bash
      run: shards build hace
