name: Build E2E Test Binaries
description: Build Crystal example binaries and upload as artifact
inputs:
  artifact-name:
    description: Name for the uploaded artifact
    required: true
  retention-days:
    description: Number of days to retain the artifact
    required: false
    default: "1"
runs:
  using: composite
  steps:
    - name: Build E2E test binaries
      shell: bash
      run: |
        mkdir -p bin
        crystal build examples/showcase.cr -o bin/showcase --release
        crystal build examples/simple.cr -o bin/simple --release
        crystal build examples/colors.cr -o bin/colors --release
        crystal build examples/keyboard_and_mouse.cr -o bin/kmd --release
        crystal build examples/animation.cr -o bin/animation --release
    - name: Upload binaries
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}
        path: bin/
        retention-days: ${{ inputs.retention-days }}
