name: Setup Node.js with pnpm
description: Install pnpm, setup Node.js with caching
inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: "24"
  pnpm-version:
    description: pnpm version to install
    required: false
    default: "10"
  working-directory:
    description: Directory containing package.json
    required: false
    default: e2e
  install-deps:
    description: Whether to run pnpm install
    required: false
    default: "true"
  frozen-lockfile:
    description: Use --frozen-lockfile flag
    required: false
    default: "true"
  ignore-scripts:
    description: Use --ignore-scripts flag
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        FLAGS=""
        if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
          FLAGS="$FLAGS --frozen-lockfile"
        fi
        if [ "${{ inputs.ignore-scripts }}" = "true" ]; then
          FLAGS="$FLAGS --ignore-scripts"
        fi
        pnpm install $FLAGS
